service:
  name: gochiusamonitoring

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  stackName: gochiusa-monitoring
  role: arn:aws:iam::646279979860:role/gochiusa_monitoring_metrics

functions:
  gochiusa-monitoring:
    handler: src/handler.entrypoint
