service:
  name: gochiusamonitoring

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  inversify:
    handler: src/handler.entrypoint
